version: '3.7'
networks:
  app-network:

services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: 'ghcr.io/thanostsiamis/fiona/api-service:latest'  # Update with your GitHub username and repo
    volumes:
      - './api:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
      - "FLASK_CONFIG=development"
    networks:
      - app-network

  client-service:
    build:
      context: ./client_side
      dockerfile: Dockerfile
    image: 'ghcr.io/thanostsiamis/fiona/client-service:latest'
    volumes:
      - './client_side:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=development"
      - "REACT_APP_SERVICE_URL=http://localhost:8080"
      - "CHOKIDAR_USEPOLLING=true"
    depends_on:
      - api-service
    networks:
      - app-network
